@baseUrl = https://0b5ff8b0.uqcloud.net/
@jwtToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic3R1ZGVudCIsInVzZXJuYW1lIjoiczQ3NTk0ODcifQ.PYGpsxjuzysuzHIad-l5VO9MbEYNBhx9X5QSfq4lMuw

### Health
GET {{baseUrl}}/api/health

### Get all emails from the server
GET {{baseUrl}}/api/project
Authorization: Bearer {{jwtToken}}

{
    "username": "s4759487"
}

### post a TEST_ITEM on the server at /customers/<string:customer_id>/emails, id is UUID
POST {{baseUrl}}/api/project
Authorization: Bearer {{jwtToken}}
Content-Type: application/json

{
    "username": "s4759487",
    "title": "Important information about your account.",
    "description": "Dear customer,\nWe have noticed some suspicious activity on your account. Please click [here](https://scam-check.uq.edu.au?userId=uqehugh3) to reset your password or [here](https://scamer-checker.uq.edu.au) to go."
}


### Delete
DELETE {{baseUrl}}/api/project?id=eq.2030
Authorization: Bearer {{jwtToken}}
Content-Type: application/json
    
    {
        "username": "s4759487"
    }
